####################################################
#                                                  #
#                Home Assistant                    #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: "Europe/Stockholm"
  currency: SEK
  external_url: !secret external_url
  internal_url: !secret internal_url
  customize:
    binary_sensor.dorrsensor_bad_access_control_window_door_is_open:
      friendly_name: "DÖRR BADRUM "
    binary_sensor.dorrsensor_forrad_access_control_window_door_is_open:
      friendly_name: "DÖRR FÖRRÅD "
    binary_sensor.dorrsensor_kok_access_control_window_door_is_open:
      friendly_name: "DÖRR KÖK "
    binary_sensor.vadring_access_control_window_door_is_open:
      friendly_name: "FÖNSTER KÖK "
    binary_sensor.dorrsensor_vardagsrum_access_control_window_door_is_open:
      friendly_name: "DÖRR VARDAGSRUM "
    binary_sensor.vadring2_access_control_window_door_is_open:
      friendly_name: "FÖNSTER VARDAGSRUM "
    binary_sensor.dorrsensor_sovrum_access_control_window_door_is_open:
      friendly_name: "DÖRR SOVRUM "
    sun.sun:
      friendly_name: "SOLEN "
    device_tracker.samsung_s20_ultra_5g:
      friendly_name: "MOBILELEFON "
  customize_domain:
    automation:
      initial_state: on
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.66.0/24
      allow_bypass_login: true

####################################################
#                                                  #
#                Default Config                    #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/default_config/
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

####################################################
#                                                  #
#                  Automations                     #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/automation/
automation: !include automations.yaml

####################################################
#                                                  #
#                    Cloud                         #
#                                                  #
####################################################
cloud:
  google_actions:
    filter:
      include_entities:
        - input_boolean.googlehome_natt_dag

#config
#counter:
#dhcp:
#energy:

####################################################
#                                                  #
#               Frontend/Themes                    #
#                                                  #
####################################################
frontend:
  themes: !include_dir_merge_named themes/

####################################################
#                                                  #
#                   History                        #
#                                                  #
####################################################
history:
  use_include_order: true
  include:
    entities:
      - sun.sun
      - device_tracker.samsung_s20_ultra_5g
      - binary_sensor.dorrsensor_bad_access_control_window_door_is_open
      - binary_sensor.dorrsensor_forrad_access_control_window_door_is_open
      - binary_sensor.dorrsensor_kok_access_control_window_door_is_open
      - binary_sensor.vadring_access_control_window_door_is_open
      - binary_sensor.dorrsensor_vardagsrum_access_control_window_door_is_open
      - binary_sensor.vadring2_access_control_window_door_is_open
      - binary_sensor.dorrsensor_sovrum_access_control_window_door_is_open
      
#image:

####################################################
#                                                  #
#                  input_boolean                   #
#                                                  #
####################################################
input_boolean:
  google_on_off:
    name: Google auto <-> manuel
    icon: mdi:google-assistant

#input_button:

####################################################
#                                                  #
#                  input_date_time                 #
#                                                  #
####################################################
input_datetime:
  both_date_and_time:
    name: Input with both date and time
    has_date: true
    has_time: true
  only_date:
    name: Input with only date
    has_date: true
    has_time: false
  only_time:
    name: Input with only time
    has_date: false
    has_time: true

#input_number
#input_select:
#input_text
#logbook:
#map:
#media_source:
#mobile_app:
#my:
#network:
#person:
#scene:

####################################################
#                                                  #
#                  Scripts                         #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/script/
script: !include scripts.yaml

#ssdp:
#stream:
#sun:
#system_health:
#tag:
#timer:
#usb:
#webhooks:
#zeroconf:
#zone:

##### End of Default Config ########################

####################################################
#                                                  #
#                     Discovery                    #
#                                                  #
####################################################
discovery:
  ignore:
    - yamaha
    - logitech_mediaserver

####################################################
#                                                  #
#                     Google                       #
#                                                  #
####################################################
google:
  client_id: !secret google_id
  client_secret: !secret google_pwd

####################################################
#                                                  #
#                     HTTP                         #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/http/
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
#ssl_certificate: /ssl/fullchain.pem
#ssl_key: /ssl/privkey.pem

####################################################
#                                                  #
#                     Logger                       #
#                                                  #
####################################################
logger:
  default: info
  logs:
    homeassistant.helpers.template: error

####################################################
#                                                  #
#                     Lovelace                     #
#                                                  #
####################################################
lovelace:
  mode: storage
  resources:
    - url: https://fonts.googleapis.com/css?family=Comfortaa&display=swap
      type: css
    - url: /local/mini-graph-card-bundle.js?v=0.10.0
      type: module
    - url: https://unpkg.com/moment@2.29.1/min/moment-with-locales.js
      type: module
    - url: /local/banner-card.js?v=1
      type: module
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module

####################################################
#                                                  #
#                 Netatmo                          #
#                                                  #
####################################################
netatmo:
  client_id: !secret netatmo_id
  client_secret: !secret netatmo_pwd

####################################################
#                                                  #
#                 Notify                           #
#                                                  #
####################################################
notify:
  - platform: group
    name: Notify Group
    services:
      - service: mobile_app_sm_g988b
  - platform: smtp
    name: !secret notify_name
    sender: !secret notify_sender
    recipient: !secret notify_recipient
    server: !secret notify_server
    port: 25
    encryption: none
    sender_name: HomeAssistant

####################################################
#                                                  #
#                   Recorder                       #
#                                                  #
####################################################
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 10
  commit_interval: 1
  exclude:
    domains:
      - media_player
      - scene
      - script
      - update
      - weather
    entities:
      - sensor.backup_state
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.backup_state
      - sensor.internet_time
  
####################################################
#                                                  #
#                 Sensors                          #
#                                                  #
####################################################
sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"

  - platform: template
    sensors:
      lights_on_count:
        friendly_name: LightsCounter
        value_template: >-
          {% set lights = [
            states.light.sovrummet,
            states.light.bord,
            states.light.forrad,
            states.light.hue_color_floor_1,
            states.light.kok,
            states.light.sang,
            states.light.sekretar,
            states.light.sovrummet,
            states.light.spirallampa,
            states.light.vardagsrum,
            states.light.badrummet,
            states.switch.badrumskap,
            states.switch.arbetsbord,
            states.switch.hallampa,
            states.switch.gangen
            ] %}
          {{ lights | selectattr('state','eq','on') | list | count }}

####################################################
#                                                  #
#                 Shell Commands                   #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/shell_command/
shell_command:
  disco_off: !secret disco_off
  disco_on: !secret disco_on
  pushupdates_to_github: !secret github

####################################################
#                                                  #
#                     TTS                          #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/tts/
# Text to speech
tts:
  - platform: google_translate
    language: en
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say
    base_url: http://192.168.66.10:8123

template: !include template.yaml
