####################################################
#                                                  #
#                Home Assistant                    #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: "Europe/Stockholm"
  currency: SEK
  external_url: !secret external_url
  internal_url: !secret internal_url
  customize_domain:
    automation:
      initial_state: on
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.66.0/24
      allow_bypass_login: true

####################################################
#                                                  #
#                Default Config                    #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/default_config/
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

####################################################
#                                                  #
#                  Automations                     #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/automation/
automation: !include automations.yaml

####################################################
#                                                  #
#                    Cloud                         #
#                                                  #
####################################################
cloud:
  google_actions:
    filter:
      include_entities:
        - input_boolean.googlehome_natt_dag
#    include_domains:
#      - switch
#    exclude_entities:
#      - switch.outside
#  entity_config:
#    switch.kitchen:
#      name: Custom Name for Google Assistant
#      aliases:
#       - bright lights
#       - entry lights
#      room: living room

#config
#counter:
#dhcp:
#energy:

####################################################
#                                                  #
#               Frontend/Themes                    #
#                                                  #
####################################################
frontend:
  themes: !include_dir_merge_named themes/

####################################################
#                                                  #
#                   History                        #
#                                                  #
####################################################
history:
  use_include_order: true
  include:
    domains:
      - switch
      - light
    entities:
      - device_tracker.samsung_s20_ultra_5g
  exclude:
    domains:
      - media_player
      - updater
    entities:
      - switch.hallampa_2
      - switch.gangen_2
      - switch.badrumskap_2

#image:
input_boolean: !include_dir_named input_boolean/
#input_button:
input_datetime: !include_dir_named input_datetime/
#input_number
#input_select:
#input_text
#logbook:
#map:
#media_source:
#mobile_app:
#my:
#network:
#person:
scene: !include scenes.yaml

####################################################
#                                                  #
#                  Scripts                         #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/script/
script: !include scripts.yaml

#ssdp:
#stream:
#sun:
#system_health:
#tag:
#timer:
#usb:
#webhooks:
#zeroconf:
#zone:
# End of Default Config ############################

####################################################
#                                                  #
#                     Discovery                    #
#                                                  #
####################################################
discovery:
  ignore:
    - yamaha
    - logitech_mediaserver

####################################################
#                                                  #
#                     Google                       #
#                                                  #
####################################################
google:
  client_id: !secret google_id
  client_secret: !secret google_pwd

####################################################
#                                                  #
#                     HTTP                         #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/http/
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: false
  login_attempts_threshold: 3
#ssl_certificate: /ssl/fullchain.pem
#ssl_key: /ssl/privkey.pem

####################################################
#                                                  #
#                     InfluxDB                     #
#                                                  #
####################################################
influxdb:
  host: 192.168.66.10
  port: 8086
  database: homeassistant
  username: !secret influxuser
  password: !secret influxpass
  max_retries: 9
  default_measurement: state

####################################################
#                                                  #
#                     Logger                       #
#                                                  #
####################################################
logger:
  default: info
  logs:
    homeassistant.helpers.template: error

####################################################
#                                                  #
#                     Lovelace                     #
#                                                  #
####################################################
lovelace:
  mode: storage
  resources:
    - url: https://fonts.googleapis.com/css?family=Comfortaa&display=swap
      type: css
    - url: /local/mini-graph-card-bundle.js?v=0.10.0
      type: module
    - url: https://unpkg.com/moment@2.29.1/min/moment-with-locales.js
      type: module
    - url: /local/banner-card.js?v=1
      type: module
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module

####################################################
#                                                  #
#                 Media player                     #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/media_player/
media_player:
  - platform: frontier_silicon
    host: 192.168.66.117
    name: Revo Radio
#- platform: cast
#  name: Nest HUB
#  host: 192.168.66.119

####################################################
#                                                  #
#                 Netatmo                          #
#                                                  #
####################################################
netatmo:
  client_id: !secret netatmo_id
  client_secret: !secret netatmo_pwd

####################################################
#                                                  #
#                 Notify                           #
#                                                  #
####################################################
notify:
  - platform: group
    name: Notify Group
    services:
      - service: mobile_app_sm_g988b
  - platform: smtp
    name: !secret notify_name
    sender: !secret notify_sender
    recipient: !secret notify_recipient
    server: !secret notify_server
    port: 25
    encryption: none
    sender_name: HomeAssistant

####################################################
#                                                  #
#                   Recorder                       #
#                                                  #
####################################################
recorder:
  db_url: !secret mariadb_url
  commit_interval: 30

####################################################
#                                                  #
#                 Sensors                          #
#                                                  #
####################################################
sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"

  - platform: template
    sensors:
      lights_on_count:
        friendly_name: LightsCounter
        value_template: >-
          {% set lights = [
            states.light.sovrummet,
            states.light.bord,
            states.light.forrad,
            states.light.hue_color_floor_1,
            states.light.kok,
            states.light.sang,
            states.light.sekretar,
            states.light.sovrummet,
            states.light.spirallampa,
            states.light.vardagsrum,
            states.light.badrummet,
            states.switch.badrumskap,
            states.switch.arbetsbord,
            states.switch.hallampa,
            states.switch.gangen
            ] %}
          {{ lights | selectattr('state','eq','on') | list | count }}

####################################################
#                                                  #
#                 Shell Commands                   #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/shell_command/
shell_command:
  disco_off: echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/serial/by-id/usb-0658_0200-if00
  disco_on: echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/serial/by-id/usb-0658_0200-if00
  pushupdates_to_github: /bin/bash pushupdates.sh

####################################################
#                                                  #
#                     TTS                          #
#                                                  #
####################################################
# https://www.home-assistant.io/integrations/tts/
# Text to speech
tts:
  - platform: google_translate
    language: en
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say
    base_url: http://192.168.66.10:8123
